core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simple_form.urls'))
]

simple_form/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('check-username', views.check_username, name='check-username'),
    path('check-subject', views.check_subject, name='check-subject')
]

simple_form/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):

    class Subjects(models.IntegerChoices):
        WEB_DEVELOPMENT = 1
        SYSTEMS_PROGRAMMING = 2
        DATA_SCIENCE = 3
    
    subject = models.PositiveSmallIntegerField(choices=Subjects.choices)
    date_of_birth = models.DateField()

simple_form/forms.py
from django import forms
from datetime import datetime
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


from .models import User 

class UniversityForm(forms.ModelForm):
    
    #name = forms.CharField()
    subject = forms.ChoiceField(choices=User.Subjects.choices, 
                widget=forms.Select(attrs={
                'hx-get' : reverse_lazy('check-subject'),
                'hx-target' : '#div_id_subject',
                'hx-trigger' : 'change',
                'hx-include': '[name="date_of_birth"], [name="password"] , [name="username"]'
            }))
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'max': datetime.now().date()}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        #self.helper.form_action = reverse_lazy('index')
        #self.helper.form_method = 'POST'
        self.helper.form_id = 'university-form'
        self.helper.attrs = {
            'hx-post' : reverse_lazy('index'),
            'hx-target' : '#university-form',
            'hx-swap' : 'outerHTML'
        }
        self.helper.add_input(Submit('submit', 'Submit'))
        #self.fields['name'].widget.attrs['hx-trigger'] = 'keyup'
        #self.fields['name'].widget.attrs['hx-get'] = reverse_lazy('index')

    class Meta:
        model = User
        fields = ('username','password','date_of_birth','subject')
        widgets = {
            'password' : forms.PasswordInput(),
            'username' : forms.TextInput(attrs={
                'hx-get' : reverse_lazy('check-username'),
                'hx-trigger' : 'keyup changed',
                'hx-target' : '#div_id_username',
                'hx-include': '[name="date_of_birth"], [name="password"] , [name="subject"]'      
            }),
        }
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) <= 3:
            raise forms.ValidationError("Username is too short")
        elif len(username) > 20:
            raise forms.ValidationError("Username Too Long")
        return username

    def clean_subject(self):
        subject = self.cleaned_data['subject']
        if User.objects.filter(subject = subject).count() >= 3:
            raise forms.ValidationError("There is no space for this subject")
        return subject

    def save(self, commit=True):                
        """ Hash user's password on save """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

simple_form/views.py
from re import X
from tempfile import tempdir
from django.http import HttpResponse
from django.shortcuts import render
from django.template.context_processors import csrf
from crispy_forms.utils import render_crispy_form
from django.contrib.auth import login

from crispy_forms.templatetags.crispy_forms_filters import as_crispy_field

from .forms import UniversityForm
# Create your views here.

def index(request):
    if request.method == "GET":
        form = UniversityForm()
        context={
            "form" : form,
        }
        return render(request, "index.html", context)
    
    elif request.method == "POST":
        form = UniversityForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            template = render(request, 'profile.html')
            template['Hx-Push'] = '/profile/'
            return template

        else:
            ctx = {}
            ctx.update(csrf(request))
            form_html = render_crispy_form(form, context=ctx)
            return HttpResponse(form_html)
            

#def check_username(request):
    #form = UniversityForm(request.GET)
    # print(as_crispy_field(form['username']))    # request.GET => {'username' : ['username inputuna ne yazdıysan onu getiriyor]}
                                                # as_crispy_field(form['username]) => 

    #return HttpResponse(as_crispy_field(form['username']))

def check_username(request):
    form = UniversityForm(request.GET)
    if form.is_valid():
        valid = True
    else:
        valid = False    
    
    context = {
        'field' : as_crispy_field(form['username']),
        'valid' : valid
    }
    
    return render(request, 'partials/field.html', context)

#def check_subject(request):
#    form = UniversityForm(request.GET)
#   return HttpResponse(as_crispy_field(form['subject']))

def check_subject(request):
    form = UniversityForm(request.GET)
    if form.is_valid():
        valid = True
    else:
        valid = False    
    
    context = {
        'field' : as_crispy_field(form['subject']),
        'valid' : valid
    }
    return render(request, 'partials/field.html', context)

simple_form/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-CrispyFormValidation-HTMX</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
</head>
<body>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

simple_form/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}


{% endblock %}

simple_form/templates/partials/field.html
{{field|safe}}

{% if valid %}
    <input type="submit" 
            name="submit" 
            value="Submit" 
            class="btn btn-primary" 
            id="submit-id-submit"
            hx-swap-oob='true'>
{% else %}
    <input type="submit" 
                name="submit" 
                value="Submit" 
                class="btn btn-primary" 
                id="submit-id-submit"
                hx-swap-oob='true'
                disabled>
{% endif %}

simple_form/templates/profile.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<h1>{{ request.user.username }}</h1>

<p>You are studying {{ request.user.get_subject_display }}</p>

{% csrf_token %}
<button hx-post="{% url 'logout' %}" hx-push-url='/' hx-target='closest body'>Logout</button>

{% else %}

<h1>You are not allowed</h1>

{% endif %}

<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
{% endblock %}